name: Python Test
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    # 关键配置：指定工作目录
    defaults:
      run:
        working-directory: ./06_03

    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with: 
          python-version: "3.11"
          
      - run: pip install -r requirements.txt
        # 在指定子目录下寻找 requirements.txt
        
      - run: python -m pytest test
        # 在指定子目录下运行测试